### ISSUE TITLE
Searching in 1st level

### ISSUE THREAD

**Issue by oblalex** [vandersonmota/t_dict#3]
Hi!

If you try to search not existing key, it's ok (as in example):

    >>> from t_dict.t_dict import TDict
    >>> td = TDict({'nested': { 'dict': 'here' }})
    >>> td.find('/nested/notfound')
    >>>

But if you will try to search at the 1st level like

    >>> td.find('/notfound')

then you'll get a `KeyError`:

     Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "/home/alex/.virtualenvs/mission-parser-demo/local/lib/python2.7/site-packages/t_dict/t_dict.py", line 41, in find
        return resolve_pointer(self, path, default)
      File "/home/alex/.virtualenvs/mission-parser-demo/local/lib/python2.7/site-packages/jsonpointer.py", line 106, in resolve_pointer
        return pointer.resolve(doc, default)
      File "/home/alex/.virtualenvs/mission-parser-demo/local/lib/python2.7/site-packages/jsonpointer.py", line 163, in resolve
        doc = self.walk(doc, part)
      File "/home/alex/.virtualenvs/mission-parser-demo/local/lib/python2.7/site-packages/jsonpointer.py", line 243, in walk
        return doc[part]
      File "/home/alex/.virtualenvs/mission-parser-demo/local/lib/python2.7/site-packages/t_dict/t_dict.py", line 23, in __getitem__
        return self.__d[key]
    KeyError: u'notfound'

**Comment by avanov** [comment]
Was the fix released on PyPI?

**Comment by vandersonmota** [comment]
@avanov not yet. I'll start to develop new features next week and will make a release by the end of this month.

**Comment by avanov** [comment]
@vandersonmota ok, look forward to it!

**Comment by vandersonmota** [comment]
done. Thank you all, people!

**Comment by o3bvv** [comment]
Thank you! :+1:

**Comment by avanov** [comment]
:+1: thanks for the release!
